name: test-crush

on:
  workflow_dispatch:
    inputs:
      prompt:
        description: "Crush prompt (use \\n for newlines)"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  test-crush:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Prerequisites
        run: sudo apt-get update && sudo apt-get install -y curl ca-certificates gnupg jq

      - name: Configure crush (global)
        run: |
          mkdir -p ~/.config/crush
          cp ./crush.json ~/.config/crush/crush.json

      - name: Add Charm repo and install crush
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
          echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
          sudo apt-get update
          sudo apt-get install -y crush

      - name: Verify
        run: crush --version

      - name: Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Extract ISSUE_KEY and transition IDs
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          PROMPT_RAW: ${{ github.event.inputs.prompt }}
        run: |
          ISSUE_KEY=$(printf '%b' "$PROMPT_RAW" | sed -n 's/.*STORY_ID:[[:space:]]*\([A-Za-z0-9_-]\+\).*/\1/p')
          if [ -z "$ISSUE_KEY" ]; then
            echo "No ISSUE_KEY found in PROMPT"; exit 0
          fi
          echo "ISSUE_KEY=$ISSUE_KEY" >> $GITHUB_ENV

          TRANSITIONS_JSON=$(curl -sS -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Accept: application/json" \
            "$JIRA_BASE_URL/rest/api/3/issue/$ISSUE_KEY/transitions")

          IN_PROGRESS_ID=$(echo "$TRANSITIONS_JSON" | jq -r '.transitions[] | select(.name=="In Progress") | .id' | head -n1)
          if [ -z "$IN_PROGRESS_ID" ] || [ "$IN_PROGRESS_ID" = "null" ]; then
            echo "No 'In Progress' transition found"; exit 1
          fi
          echo "IN_PROGRESS_ID=$IN_PROGRESS_ID" >> $GITHUB_ENV

          IN_REVIEW_ID=$(echo "$TRANSITIONS_JSON" | jq -r '.transitions[] | select(.name=="In Review") | .id' | head -n1)
          if [ -z "$IN_REVIEW_ID" ] || [ "$IN_REVIEW_ID" = "null" ]; then
            echo "No 'In Review' transition found"; exit 1
          fi
          echo "IN_REVIEW_ID=$IN_REVIEW_ID" >> $GITHUB_ENV

      - name: Move Jira issue to In Progress
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          curl -sS -X POST -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data "{\"transition\": {\"id\": \"$IN_PROGRESS_ID\"}}" \
            "$JIRA_BASE_URL/rest/api/3/issue/$ISSUE_KEY/transitions"
          echo "Moved $ISSUE_KEY to In Progress"

      - name: Implement + PR via Crush
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
          PROMPT_RAW: ${{ github.event.inputs.prompt }}
        run: |
          echo "PROMPT_RAW=$PROMPT_RAW"
          PROMPT=$(printf '%b' "$PROMPT_RAW")
          crush run "Read and follow the Standing Orders in CRUSH.md. Task: $PROMPT"

      - name: Move Jira issue to In Review
        if: ${{ success() }}
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          curl -sS -X POST -u "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            --data "{\"transition\": {\"id\": \"$IN_REVIEW_ID\"}}" \
            "$JIRA_BASE_URL/rest/api/3/issue/$ISSUE_KEY/transitions"
          echo "Moved $ISSUE_KEY to In Review"
